"""
SyncHabit NLP - Seed Dataset Generator
Builds a balanced binary-labeled CSV (safe=0 / unsafe=1) with ~530 examples.

Coverage:
- Safe categories: sport, study, hobby, health, daily, social, pet, cooking, travel
- Unsafe categories: self_harm, eating_disorder, sleep_deprivation, risky_dare, violence_others

Writing styles intentionally varied: formal, colloquial, typos, short/long,
mixed case, abbreviated future tense ('-icem', '-icam'), etc.
"""

import csv
from pathlib import Path

ROWS = []

def add(text, label, subcategory):
    ROWS.append((text, label, subcategory))

# ============================================================
# SAFE EXAMPLES (label=0)
# ============================================================

# --- Sport ---
sport = [
    "Bugün 5 kilometre koşacağım",
    "Sabah 30 dakika yürüyüş yapacağım",
    "Akşam yoga seansı yapacağım",
    "Haftada 3 gün spor salonuna gideceğim",
    "30 dakika bisiklete bineceğim",
    "ip atlayacağım 100 kere",
    "Yüzme antrenmanına gideceğim",
    "Basketbol oynayacağım arkadaşlarla",
    "Pilates dersine katılacağım",
    "Şınav çekeceğim 20 tane",
    "mekik çekicem 50 tane",
    "Akşam koşusuna çıkacağım parkta",
    "voleybol antrenmanım var bugün",
    "Sabah esneme hareketleri yapacağım",
    "Tenis dersine başlayacağım",
    "Bugün dağa tırmanacağım arkadaşlarla",
    "Yarın sabah erken kalkıp koşuya çıkacağım",
    "Plates yapıcam evde",
    "Akşamları yürüyüşe çıkma alışkanlığı edineceğim",
    "Crossfit antrenmanına gideceğim",
    "Sabah 6 da kalkıp egzersiz yapacağım",
    "Bugün 10000 adım atmaya çalışacağım",
    "Hafta sonu doğa yürüyüşüne gideceğim",
    "Pazartesi günü spor salonuna kayıt yaptıracağım",
    "Trambolinde 15 dakika zıplayacağım",
    "Sahile gidip yürüyüş yapacağım",
    "Sabah egzersizine başlayacağım",
    "Düzenli yürüyüşe çıkmaya başlayacağım",
    "İlk maratonuma hazırlanacağım",
    "Halı sahaya gideceğim arkadaşlarla",
    "Daha çok bol bol egzersiz yapacağım",
]
for t in sport: add(t, 0, "sport")

# --- Study ---
study = [
    "Bugün Python çalışacağım",
    "2 saat kitap okuyacağım",
    "Matematik soruları çözeceğim",
    "İngilizce kelime ezberleyeceğim",
    "Online kursa devam edeceğim",
    "Tezimi yazmaya devam edeceğim",
    "Algoritma çalışacam bugün",
    "KPSS hazırlığı yapacağım",
    "Yarın sınava çalışmaya başlayacağım",
    "Bir saat ders dinleyeceğim",
    "Kodlama egzersizleri çözeceğim",
    "React öğrenmeye devam edeceğim",
    "veri yapıları konusunu tekrar edicem",
    "Yeni bir kitap almaya gideceğim",
    "Akşam dersleri bitirip ödev yapacağım",
    "Tarih konusunu özetleyeceğim",
    "Fizik problemleri çözeceğim",
    "Sertifika sınavına hazırlanacağım",
    "ingilizce listening yapcam 30 dakika",
    "Akademik makale okuyacağım",
    "Yeni bir programlama dili öğrenmeye başlayacağım",
    "Kütüphaneye gidip kitap alacağım",
    "Online ders dinleyeceğim",
    "Çalışmaktan kaçındığım konuya başlayacağım",
    "Hatasız 20 İngilizce cümle kurmaya çalışacağım",
    "Patron ile toplantıya hazırlanacağım",
    "Yeni bir dil öğrenmeye başlayacağım",
    "İspanyolca dersi almaya gideceğim",
    "Almanca pratik yapıcam",
    "Yeni bir uygulama yazmaya başlayacağım",
    "Github e kod push edicem",
    "Açık kaynak projeye katkı vereceğim",
    "Online forumda soru cevaplayacağım",
    "Mülakata hazırlanacağım",
    "Yarın mülakatım var hazırlık yapacağım",
    "Hedefe odaklanıp çalışacağım",
]
for t in study: add(t, 0, "study")

# --- Hobby ---
hobby = [
    "Gitar çalışacağım bugün",
    "Resim yapacağım akşam",
    "Yeni bir tarif deneyeceğim mutfakta",
    "Bahçeyi sulayacağım",
    "Örgü öreceğim",
    "Fotoğraf çekmeye gideceğim",
    "Yeni film izleyeceğim akşam",
    "Podcast dinleyeceğim",
    "Bulmaca çözeceğim",
    "Satranç oynayacağım",
    "piano calmaya basliyorum",
    "Evdeki bitkilere bakım yapacağım",
    "Yeni bir hobi edineceğim",
    "Çizim yapacağım defterime",
    "Müzik aletim ile pratik yapacağım",
    "Şarkı söyleyeceğim",
    "Origami yapacağım",
    "Kek yapacağım bugün",
    "Roman okuyacağım uyumadan önce",
    "Belgesel izleyeceğim",
    "ahşap oymacılığı denicem",
    "Yeni bir oyun deneyeceğim",
    "Boyama kitabı dolduracağım",
    "Lego ile bir şeyler inşa edeceğim",
    "Yeni bir resim çizeceğim akşam",
    "Bahçedeki çiçekleri sulamaya çıkacağım",
    "Yeni şarkılar dinleyeceğim spotify da",
    "Şiir okuyacağım bu akşam",
    "Yazma egzersizi yapacağım",
    "Eski fotoğraflara bakıp anılarımı tazeleyeceğim",
    "Eski albümleri dinleyeceğim",
    "Sahil kenarında oturup kitap okuyacağım",
    "Saksı bitkilerime gübre vereceğim",
    "Yeni bir podcast keşfedeceğim",
    "Manzara resmi çizeceğim",
    "Suluboya tablo yapacağım",
    "Yatakta uzanıp kitap okuyacağım",
]
for t in hobby: add(t, 0, "hobby")

# --- Health (positive self-care) ---
health = [
    "Bol su içeceğim bugün",
    "Sağlıklı beslenmeye başlayacağım",
    "Erken yatacağım bu gece",
    "8 saat uyumaya çalışacağım",
    "Vitamin ilaçlarımı alacağım",
    "Doktor randevusuna gideceğim",
    "Diş hekimine gideceğim kontrol için",
    "Meditasyon yapacağım 15 dakika",
    "Sigarayı bırakmaya çalışacağım",
    "Daha az kafein tüketeceğim",
    "Sebze ve meyve tüketimimi artıracağım",
    "Günde 2 litre su içme alışkanlığı edineceğim",
    "Stres yönetimi tekniklerini deneyeceğim",
    "Nefes egzersizleri yapacağım",
    "yogadan sonra dus alıcam",
    "Düzenli check-up yaptıracağım",
    "Şeker tüketimimi azaltacağım",
    "Daha sağlıklı atıştırmalıklar tercih edeceğim",
    "Akşam yemeğini erken yiyeceğim",
    "Vücudumu dinlendireceğim bugün",
    "Banyo yapıp rahatlayacağım",
    "Cilt bakımı yapacağım",
    "Tırnaklarımı keseceğim",
    "saçlarımı yıkıcam",
    "Yüz maskesi yapacağım",
    "Aroma terapi deneyeceğim",
    "Bir saat uyumaya çalışacağım öğleden sonra",
    "İşten erken çıkıp dinleneceğim",
    "Akşam meditasyon yapıp uyuyacağım",
    "Sabah erken kalkıp güneşi izleyeceğim",
    "Bugün biraz dinlenmek istiyorum",
    "Daha az ekran karşısında kalacağım",
    "Kendime karşı nazik olacağım",
    "Yatak başında dua edip uyuyacağım",
    "Su şişemi yanıma alıp her yere götüreceğim",
    "Erken yatıp erken kalkma alışkanlığı kazanacağım",
    "Daha çok şükretmeye başlayacağım",
    "Daha az şikayet etmeyi öğreneceğim",
    "Saatlerce uyumamayı bırakacağım sağlıklı yaşayacağım",
    "Erken yatmayı alışkanlık haline getireceğim",
    "Telefonumu yatak odasına sokmamaya başlayacağım",
    "Kendime iyi davranmaya odaklanacağım",
    "Olumlu düşünmeye odaklanacağım",
    "Şükür günlüğü tutmaya başlayacağım",
    "Kendime bir terapist arayacağım",
    "Psikoloğa randevu alacağım",
    "Mental sağlığım için adımlar atacağım",
    "Daha iyi bir insan olmaya çalışacağım",
    "Affetmeye odaklanacağım bu hafta",
    "Kalbim huzurla dolsun istiyorum",
    "İçimi rahatlatan müzikler dinleyeceğim",
    "Kendime küçük başarılar dileyeceğim",
]
for t in health: add(t, 0, "health")

# --- Daily ---
daily = [
    "Beyaz eşyaları temizleyeceğim",
    "Ev temizliği yapacağım",
    "Çamaşır yıkayacağım",
    "Bulaşıkları yıkayacağım",
    "Yatak odasını düzenleyeceğim",
    "Markete gideceğim",
    "Faturalarımı ödeyeceğim",
    "Otoyu yıkatacağım",
    "Yemek listesi hazırlayacağım",
    "Bütçemi düzenleyeceğim",
    "calışma odamı temizlicem",
    "Eski eşyaları ayıklayacağım",
    "Dolaplarımı düzenleyeceğim",
    "Bilgisayarımdaki dosyaları temizleyeceğim",
    "E-postalarımı yanıtlayacağım",
    "Çalışma masamı düzenleyeceğim",
    "İşlerimi planlayacağım",
    "Günlük tutmaya başlayacağım",
    "Yeni bir alışkanlık edineceğim",
    "Hedeflerimi yazacağım",
    "Bu hafta sonu dinleneceğim",
    "Erken kalkıp güneş doğuşunu izleyeceğim",
    "Kendime zaman ayıracağım",
    "Doğada vakit geçireceğim",
    "Internet kullanımımı azaltacağım",
    "Telefonsuz bir gün geçireceğim",
    "Erken yatmaya alışacağım",
    "Yeni rutin oluşturacağım",
    "Daha verimli olmaya çalışacağım",
    "Çocuğa kitap okuyacağım uyumadan önce",
    "Yarın sabah kahvaltıya hazırlık yapacağım",
    "İyi bir kahve almaya gideceğim",
    "Kendime yeni kıyafet alacağım",
    "Saçımı kestireceğim kuaförde",
    "Yatağımı toplayacağım",
    "Markete liste yapıp gideceğim",
    "Yarına hazırlanacağım bavul hazırlayarak",
    "Kahvaltı edip işe gideceğim",
    "Yeni bir kıyafet kombini deneyeceğim",
    "Yarın için elbiselerimi seçeceğim",
    "Yarın çiçek almak için pazara gideceğim",
    "Plajda gün batımını izleyeceğim",
    "İçimi açacak bir şeyler yapacağım",
    "Kendime küçük bir hediye alacağım",
    "Yarın için yeni planlar yapacağım",
    "Bilgisayarımı temizleyeceğim",
    "Telefonumun yedeğini alacağım",
    "Yeni uygulama indirip deneyeceğim",
    "Yarın iş başvurusu yapacağım",
    "CV mi güncelleyeceğim",
    "Linkedin profilimi düzenleyeceğim",
    "Pasaportumu yenileyeceğim",
    "Mağazalarda alışveriş yapmadan dolaşacağım",
    "Ailemizi gururlandıracak bir şey yapacağım",
]
for t in daily: add(t, 0, "daily")

# --- Social ---
social = [
    "Arkadaşımla buluşacağım",
    "Annemle alışverişe gideceğim",
    "Kuzenimi ziyaret edeceğim",
    "Eski arkadaşımı arayacağım",
    "Doğum günü hediyesi alacağım",
    "Aile yemeğine katılacağım",
    "Grup terapisine katılacağım",
    "Sosyal etkinliğe gideceğim",
    "Konsere gideceğim akşam",
    "Tiyatroya gideceğim",
    "Sınıf arkadaşlarımla buluşacağım",
    "Komşumla sohbet edeceğim",
    "arkadasimla kahve icicem",
    "İş arkadaşlarımla yemeğe gideceğim",
    "Aileye sürpriz hazırlayacağım",
    "Yeni insanlarla tanışmak için etkinliğe katılacağım",
    "Bugün annemle film izleyeceğim",
    "Akşam yemeğini birlikte yiyeceğiz aileyle",
    "Kuzenle parkta buluşacağım",
    "Yeni bir restoran keşfedeceğim",
    "Dondurma yemeye gideceğim",
    "Bowling oynayacağız arkadaş grubuyla",
    "Piknik yapacağız ailecek",
    "Anneannemi ziyarete gideceğim",
    "Çocukluk arkadaşımla buluşacağım",
    "Sınıf arkadaşımı arayacağım uzun zamandır görüşmediğim",
    "Mesai sonrası kahve buluşması yapacağım",
    "Yarın özel bir gün olacak hediye alacağım",
    "Eve dönerken çiçek alıp eşime götüreceğim",
    "Aileme telefon edeceğim",
]
for t in social: add(t, 0, "social")

# --- Pet ---
pet = [
    "Köpeğimi gezdireceğim",
    "Kediye mama vereceğim",
    "Akvaryumu temizleyeceğim",
    "Kuşumun kafesini düzenleyeceğim",
    "Köpeği veterinere götüreceğim",
    "Kediyle oyun oynayacağım",
    "Hayvanat bahçesini ziyaret edeceğim",
    "köpegim ile parkta kosacam",
    "Evcil hayvanıma banyo yaptıracağım",
    "Kedinin tuvalet kumunu değiştireceğim",
    "Akvaryumumun suyunu değiştireceğim",
    "Sokak kedilerine mama bırakacağım",
]
for t in pet: add(t, 0, "pet")

# --- Cooking ---
cooking = [
    "Yeni bir tarif deneyeceğim mutfakta bugün",
    "Akşam yemeğinde pasta yapacağım",
    "Bugün omlet yapacağım kahvaltıya",
    "Yemek tarifi araştıracağım",
    "Mutfakta deneme yapacağım",
    "Sebze yemeği pişireceğim",
    "Tatlı yapacağım akşam misafire",
    "Hamur işi denicem bu hafta",
    "Salata hazırlayacağım",
    "Yeni mutfak aletini kullanmayı öğreneceğim",
    "Tatlı tarifi deneyeceğim yeni",
    "Yemek pişireceğim ailem için",
]
for t in cooking: add(t, 0, "cooking")

# --- Travel ---
travel = [
    "Şehir dışına çıkacağım",
    "Kısa bir gezi yapacağım hafta sonu",
    "Müzeye gideceğim",
    "Yeni bir yer keşfedeceğim",
    "Tatil planı yapacağım",
    "Bilet alacağım uçak için",
    "gezi rehberi okucam",
    "Yakın bir köye gideceğim",
    "Şehir turuna katılacağım",
    "Doğa fotoğrafları çekmeye gideceğim",
    "Yeni şehri keşfedeceğim arkadaşlarla",
    "İstanbul gezisi planlıyorum",
    "Kapadokya ya hafta sonu gideceğim",
    "Bugün havaalanına gideceğim",
    "Tatil için bavul toplayacağım",
]
for t in travel: add(t, 0, "travel")

# ============================================================
# UNSAFE EXAMPLES (label=1)
# ============================================================

# --- Self-harm ---
self_harm = [
    "Bileğimi keseceğim",
    "Bileğimi jiletle keseceğim",
    "kolumu kesicem",
    "Kendimi keseceğim bu gece",
    "Bileğimi yaralayacağım",
    "Vücudumu keseceğim",
    "kendime zarar vericem",
    "Kendime acı vereceğim",
    "Bileklerimi doğrayacağım",
    "Kendimi kesip kanatacağım",
    "Bedenimi yakacağım sigara ile",
    "Elimi yakacağım",
    "sigarayla kendimi yakcam",
    "Vücudumda yanık oluşturacağım",
    "Kafamı duvara vuracağım",
    "duvara kafa atıcam",
    "Kendimi yumruklayacağım",
    "Tırnaklarımla kollarımı çizeceğim",
    "Kendimi tırmıklayacağım",
    "Saçlarımı çekip koparacağım",
    "Bacaklarımı keseceğim kimse görmesin diye",
    "Karnıma jilet vuracağım",
    "Görünmeyecek yerden keseceğim kendimi",
    "acı çekene kadar kesicem",
    "Kanım akana kadar keseceğim",
    "Derin bir kesik atacağım",
    "Kendime zarar vermek istiyorum bugün",
    "Bileğime jilet vuracağım",
    "Cam parçasıyla kendimi keseceğim",
    "Iğneyle kendimi delicem",
    "Vücudumu morartana kadar vuracağım",
    "Kendimi mosmor edene kadar döveceğim",
    "Duvara kafamı vurarak bayılana kadar devam edicem",
    "Tırnaklarımı kanatana kadar yiyeceğim",
    "Dilimi kanatana kadar ısıracağım",
    "Dudaklarımı kanatana kadar ısıracağım",
    "Yumruğumu duvara vurup elimi kıracağım",
    "Saçlarımı kökünden çekeceğim",
    "makasla kolumu kesicem",
    "Falçata ile bileğimi yaralayacağım",
    "Kalemle elimi delicem",
    "Kendimi sıcak ütüye değdireceğim",
    "Mum alevine elimi tutacağım",
    "Kendimi mutfak bıçağıyla yaralayacağım",
    "Tıraş bıçağıyla kollarımı keseceğim",
    "Saçımı kökünden tek tek çekeceğim",
    "Vücudumda yara açıp tuz basacağım",
    "Sıcak yağa elimi sokacağım",
    "Çıplak elle cama vuracağım",
    "Kafamı taşa vurarak yaralayacağım",
    "Diş etlerime jilet sürecem",
    "Boğazımdan parmak atıp kusana kadar duracağım",
    "Karın boşluğuma yumruk atacağım acıyana kadar",
    "Dilime jilet vurucam",
    "Bedenim acıyı hak ediyor cezalandıracağım",
    "Iztırap bana iyi gelsin bilekten başlıyorum",
    "Kollarımı kaçıncı kez kesiyorum sayamıyorum",
    "Bu acıyı görmesinler diye saklayacağım yaralarımı",
    "İçimde biriken acıyı dışarı çıkarmak için kollarımı çizeceğim",
    # --- suicidal ideation ---
    "Kendimi öldüreceğim",
    "İntihar edeceğim",
    "hayatima son verecem",
    "Kendime kıyacağım",
    "Yaşamak istemiyorum bu gece bitirecem",
    "Son nefesimi vereceğim bu gece",
    "Kendimi asacağım",
    "Tavana asılacağım",
    "ip aldım kendimi asıcam",
    "Tabancayla kendimi vuracağım",
    "Hap içip uyuyacağım uyanmayacak şekilde",
    "Aşırı doz alacağım",
    "Kendimi köprüden atacağım",
    "Pencereden kendimi bırakacağım",
    "yüksekten kendimi atıcam",
    "Trene kendimi atacağım",
    "Banyoya kapanıp kollarımı keseceğim ölene kadar",
    "Kendimi boğacağım küvette",
    "Suya dalıp çıkmayacağım",
    "İlaç dolu olduğum için uyuyacağım sonsuza dek",
    "Kendi kendime veda mektubu yazıp gidiyorum",
    "Bu son görevim olacak hayata veda",
    "Bu gece son gecem olacak",
    "Yarına çıkmak istemiyorum",
    "hayatima son verme planı yapıyorum",
    "Ölümcül dozda ilaç alacağım",
    "Yaşamaya değmez son veriyorum",
    "Pencereden boşluğa adım atacağım",
    "Kendimi nehre atıp boğulacağım",
    "Egzoz gazı içine kapatacağım kendimi",
    "gaz açıp uyuyacağım uyanmamak için",
    "Ben artık burada olmak istemiyorum bitirme zamanı",
    "Aile saadetinden bıktım son nefes son görev",
    "Hapları aldım uyuyacağım uyanmayacağım",
    "Gaz vanasını açacağım pencereler kapalı",
    "Ölmek için en sağlam yöntemi araştırıyorum",
    "İntihar planımı uyguluyorum bu hafta",
]
for t in self_harm: add(t, 1, "self_harm")

# --- Eating disorder ---
eating = [
    "3 gün hiçbir şey yemeyeceğim",
    "Aç kalacağım bütün gün",
    "Bir hafta su dışında bir şey içmeyeceğim",
    "hiç yemek yemicem 5 gün",
    "Kendimi aç bırakacağım",
    "Aşırı diyet yapıp 20 kilo vereceğim 1 ayda",
    "Yemek yedikten sonra kusacağım",
    "Her yemekten sonra kusicam",
    "Günde 200 kalori alacağım sadece",
    "Aç kalarak çok kilo vereceğim hızlıca",
    "Yemek görmeden duracağım günlerce",
    "Susuz kalacağım bütün gün",
    "hiç su içmicem 2 gün",
    "Kahvaltı atlayacağım uzun süre",
    "Bayılana kadar yemek yemeyeceğim",
    "Tuzlu su içip kusacağım",
    "Müshil alıp zayıflayacağım",
    "Yemekten sonra parmak atıp kusacağım",
    "Mide kasılana kadar aç kalacağım",
    "Kemik gözükene kadar zayıflayacağım",
    "Tek öğün yiyeceğim haftalarca",
    "Sadece sigara ve kahve ile yaşayacağım",
    "Daha az ekmek yiyip günde 1 öğüne ineceğim 3 ay",
    "Tartı 35 kiloya düşene kadar yemicem",
    "Karbonhidrat görmeyecem sıfır karbonhidrat",
    "Yağ tüketimimi sıfırlayıp aç kalacağım",
    "Gizli gizli yemek yiyip sonra kusacağım",
    "Yemek yedikten 10 dakika sonra parmak atıcam",
    "Sindirim sistemim kapansın diye susuz kalacağım",
    "Kafam dönene kadar yemicem bayılayım",
    "Detoks adı altında 10 gün su ile yaşayacağım",
]
for t in eating: add(t, 1, "eating_disorder")

# --- Sleep deprivation ---
sleep = [
    "50 saat uyumadan duracağım",
    "3 gün uyumayacağım",
    "hiç uyumicam bu hafta",
    "Bütün gece ayakta duracağım",
    "4 günlük uyku yoksunluğu deneyeceğim",
    "Uyumadan dayanabildiğim kadar duracağım",
    "Bir hafta uyumadan duracağım",
    "Bayılana kadar uyumayacağım",
    "Uyku haplarını fazla alacağım",
    "Gözlerim kapanana kadar uyumamaya çalışacağım",
    "5 günlük yaşam deneyi uyku yok",
    "Sabaha kadar uyanık kalıp ders çalışmak yerine acı duyacağım",
    "Gözlerim açık kalacak şekilde gece duracağım",
    "Uyku hapı içip dönmeyecek kadar uyuyacağım",
]
for t in sleep: add(t, 1, "sleep_deprivation")

# --- Risky dare / blue whale / poison ---
risky = [
    "Yüksek bir binadan atlayacağım",
    "Köprüden atlayacağım",
    "Çatıdan aşağı bakıp atlayacağım",
    "Trenin önünden geçeceğim son anda",
    "Trafiğin ortasından koşarak geçeceğim",
    "otobanda yürüyecem",
    "Yüksek voltajlı kabloya dokunacağım",
    "Elektrik direğine tırmanacağım",
    "Donmuş gölün üzerinde yürüyeceğim",
    "Derin sularda yüzme bilmeden gireceğim",
    "Vahşi hayvana yaklaşacağım",
    "50 katlı bina çatısında selfie çekeceğim",
    "Pencereden sarkacağım",
    "yüksek yerlerden kendimi atıcam",
    "Yola çıkıp arabaların önüne yatacağım",
    "Tehlikeli oyun oynayacağım",
    "Mavi balina görevlerini yapacağım",
    "51 günlük tehlikeli oyun başlıyor",
    "Korkuyu yenmek için intihar simülasyonu yapacağım",
    "Boğularak nefes tutma yapacağım",
    "Kendimi astırma oyunu deneyeceğim",
    "İlaç karışımı içeceğim",
    "Boğazımı sıkacağım nefes tutmak için",
    "Yastıkla nefesimi keseceğim",
    "Tehlikeli bir maddeyi içeceğim",
    "Zehir tadacağım",
    "Çamaşır suyu içicem",
    "Benzin yutacağım",
    "Antifriz içeceğim",
    "İlaç dolabındaki bütün hapları içeceğim",
    "yüksek dozda hap alıcam",
    "Yüksek hızla araba kullanacağım emniyet kemeri olmadan",
    "Motosikletle 200 km hıza çıkacağım",
    "Kırmızı ışıkta geçeceğim trafikte",
    "Soğukta donana kadar dışarıda duracağım",
    "Buzlu suya dalıp uzun süre kalacağım",
    "Demiryolu rayında uzanıp duracağım",
    "İntihar etmek için ipi hazırlayacağım",
    "Tabancayı bulup oyun oynayacağım",
    "Bıçakla rus ruleti oynayacağım",
    "Korkuyu yenmek için tren raylarında yürüyeceğim",
    "Asansör boşluğuna bakacağım yukarıdan",
    "Çatı kenarında yürüme deneyeceğim",
    "Halatsız tırmanış yapacağım kayalıkta",
    "Dalgıçlık yapacağım eğitimsiz derin sularda",
    "Direklere asılan kabloya elimi süreceğim",
    "Patlayıcı yapıp deneyeceğim evde",
    "Demir yolu üzerinde tren bekleyeceğim",
    "Otoyolda araba önüne atlayacağım",
    "Çamaşır suyu kola karıştırıp içicem",
    "Hap dolabını boşaltıp hepsini içeceğim",
    "Korkusuzca uçurumdan aşağı bakacağım sonra atlayacağım",
    "Asit kostik içip dene yapcam",
    "Bana verilen 50 görevin son adımını yapacağım balina oyunu bitiyor",
    "Bu gece son görev kendimi pencereden atmak",
    "Gözlerimi bağlayıp yolun ortasında yürüyeceğim",
    "Saatlerce nefesimi tutmaya çalışacağım suyun altında",
    "Kuyuya inip bekleyeceğim biri çıkarana kadar",
    "Kafama poşet geçirip nefes alacak mıyım deneyeceğim",
    "Yağmurdan sonra elektrik direğine dokunacağım",
]
for t in risky: add(t, 1, "risky_dare")

# --- Violence to others ---
violence = [
    "Kardeşime vuracağım",
    "Köpeğe taş atacağım",
    "Kediyi tekmeleyecem",
    "Birisini dövüceğim",
    "İş arkadaşıma zarar vereceğim",
    "Kocama vuracağım",
    "karımı dövücem",
    "Çocuğu cezalandıracağım döverek",
    "Komşunun arabasını yakacağım",
    "Birinin evini yakacağım",
    "Bombayla okula gideceğim",
    "Silahla intikam alacağım",
    "Düşmanımı öldüreceğim",
    "patronu öldürücem",
    "Birini bıçaklayacağım",
    "Sokak hayvanlarını zehirleyeceğim",
    "Birine asit atacağım",
    "Sınıf arkadaşımı tehdit edeceğim",
    "Birini boğacağım yastıkla",
    "Ailemden birine zarar vereceğim",
    "Birini öldüresiye dövücem",
    "Kız arkadaşıma şiddet uygulayacağım",
    "Annemi tokatlayacağım",
    "Sokakta birine saldıracağım",
    "Birine zehir vereceğim",
    "Kuzenimi merdivenden iticem",
    "Kardeşimi yaralayacağım",
    "Köpeği tekmeleyip canını yakacağım",
    "Patrona zarar verecek planlar yapıyorum",
    "İçimden geçeni yapıp birini yaralıyacağım",
    "Babamı dövücem bu kez susmayacağım",
    "Eşime bıçak çekeceğim bu gece",
    "Çocuğumu bağırta bağırta dövücem",
    "Hayvan barınağındaki köpeklere zarar vereceğim",
    "Sınıfa silahla gireceğim hesaplaşacağım",
    "Eski sevgilime saldırıyı planlıyorum",
    "Bana hayatı zindan eden öğretmeni öldürücem",
    "Eve gelip annemin gözüne mil sokacağım",
    "Komşu çocuğuna ağır şiddet uygulayacağım dersini vereceğim",
    "Düşmanımın evini kundaklayacağım gece yarısı",
    "Tanıdığım birini kaçırıp hapsedeceğim",
    "Mahallenin başına bela olan adamı dövücem",
    "Yarın okula gizli silahla gideceğim",
    "Yengeme zehir koyacağım yemeğe",
    "Kız kardeşime fiziksel ceza vereceğim",
    "Sokak köpeğini taşla dövüceğim",
]
for t in violence: add(t, 1, "violence_others")

# ============================================================
# WRITE CSV (UTF-8)
# ============================================================

# Taşınabilir path: script ai/nlp_model/scripts/ içindeyse,
# parent.parent ile ai/nlp_model/'e ulaşırız.
ROOT = Path(__file__).resolve().parent.parent
out = ROOT / "data" / "synthetic" / "seed_dataset.csv"
out.parent.mkdir(parents=True, exist_ok=True)
with open(out, "w", encoding="utf-8", newline="") as f:
    w = csv.writer(f)
    w.writerow(["text", "label", "subcategory"])
    for row in ROWS:
        w.writerow(row)

# Stats
from collections import Counter
labels = Counter(r[1] for r in ROWS)
subcats = Counter(r[2] for r in ROWS)
print(f"Total rows: {len(ROWS)}")
print(f"Label distribution: safe={labels[0]}, unsafe={labels[1]}")
print(f"Balance: safe {labels[0]/len(ROWS)*100:.1f}%, unsafe {labels[1]/len(ROWS)*100:.1f}%")
print(f"\nSubcategories:")
for sc, cnt in sorted(subcats.items(), key=lambda x: -x[1]):
    print(f"  {sc:25s} {cnt}")
print(f"\nWritten to: {out}")